### ISSUE TITLE
Get rid of colons in route filenames

### ISSUE THREAD

**Issue by blokhin** [PaulMaly/express-bff#1]
Please, let's get rid of colons in the route filenames (e.g. `routes/calculations/:uuid.js`) as they might cause severe rendering problems in OS file managers.

**Comment by blokhin** [comment]
@PaulMaly what do you think?

**Comment by PaulMaly** [comment]
yea, we'll handle it very soon.

**Comment by PaulMaly** [comment]
fixed in 0.7.1
